# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf5ccedc2a03f9929448d802da4497328eb361eb44e679c1b54afc388a4fd64b1bf0262103a3801c942954d87ec31469b5f3417c79dbfa55cc79f286dc3377f5

test:
  secret_key_base: f22935118909c92d0070a032ead9db1fc5c37f688ebd5164589bb8c46e34282194a1b3fa001c2e9be5c049d7f328150c501c87e13ecb76f5a50dcd26b21028fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
